### Working with real data

In [61]:
import numpy as np
import pandas as pd

In [62]:
df = pd.read_csv('amazon 1.csv')

## Practice Questions on Amazon Dataset

In [63]:
# Check the dataframe columns and their data types using `df.columns` and `df.dtypes`.

print(df.columns)
df.dtypes

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='str')

product_id             str
product_name           str
category               str
discounted_price       str
actual_price           str
discount_percentage    str
rating                 str
rating_count           str
about_product          str
user_id                str
user_name              str
review_id              str
review_title           str
review_content         str
img_link               str
product_link           str
dtype: object

In [64]:
# Remove unnecessary columns from the data frame.
df.drop(columns= ["img_link", "product_link", 'review_id','user_name','user_id','about_product','product_id'], inplace = True)

In [65]:
# Remove the currency symbols and commas from `discounted_price` and `actual_price`, then convert them to numeric values.
# Clean the price columns: remove '₹' and ',' and convert to float.

df["discounted_price"] = df["discounted_price"].str.replace("₹", "").str.replace(",", "").astype(float)

df["actual_price"] = df["actual_price"].str.replace("₹", "").str.replace(",", "").astype(float)

In [94]:
df = df[df["rating"] != "|"]

In [93]:
# Find the product with the highest `rating` and the product with the highest `rating_count`.

df.sort_values(by =["rating","rating_count"], ascending=False)[["product_name", 'rating']].head()

                                           product_name  rating
775   Amazon Basics Wireless Mouse | 2.4 GHz Connect...     5.0
174   Syncwire LTG to USB Cable for Fast Charging Co...     5.0
1145  Swiffer Instant Electric Water Heater Faucet T...     4.8
1299  Instant Pot Air Fryer, Vortex 2QT, Touch Contr...     4.8
1201  Oratech Coffee Frother electric, milk frother ...     4.8

In [68]:
#

df[df['rating'] == df['rating'].max()]['product_name']

174    Syncwire LTG to USB Cable for Fast Charging Co...
324    REDTECH USB-C to Lightning Cable 3.3FT, [Apple...
775    Amazon Basics Wireless Mouse | 2.4 GHz Connect...
Name: product_name, dtype: str

In [69]:
df.info()

<class 'pandas.DataFrame'>
Index: 1464 entries, 0 to 1464
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_name         1464 non-null   str
 1   category             1464 non-null   str
 2   discounted_price     1464 non-null   float64
 3   actual_price         1464 non-null   float64
 4   discount_percentage  1464 non-null   str
 5   rating               1464 non-null   str
 6   rating_count         1462 non-null   str
 7   review_title         1464 non-null   str
 8   review_content       1464 non-null   str
dtypes: float64(2), str(7)
memory usage: 2.6 MB

In [70]:
df["discount_percentage"] = df["discount_percentage"].str.replace("%", "").astype(float)

In [71]:
df["discount_percentage"]

0       64.0
1       43.0
2       90.0
3       53.0
4       61.0
        ...
1460    59.0
1461    25.0
1462    28.0
1463    26.0
1464    22.0
Name: discount_percentage, Length: 1464, dtype: float64

In [72]:
df["rating"] = df["rating"].astype(float)

In [73]:
df["rating_count"].dtype

In [74]:
df["rating_count"]

0       24,269
1       43,994
2        7,928
3       94,363
4       16,905
         ...
1460     1,090
1461     4,118
1462       468
1463     8,031
1464     6,987
Name: rating_count, Length: 1464, dtype: str

In [75]:
df["rating_count"] = df["rating_count"].str.replace(",", "")

In [76]:
df["rating_count"]

0       24269
1       43994
2        7928
3       94363
4       16905
        ...
1460     1090
1461     4118
1462      468
1463     8031
1464     6987
Name: rating_count, Length: 1464, dtype: str

In [77]:
df["rating_count"] = df["rating_count"].astype(float)

In [78]:
df.info()

<class 'pandas.DataFrame'>
Index: 1464 entries, 0 to 1464
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_name         1464 non-null   str
 1   category             1464 non-null   str
 2   discounted_price     1464 non-null   float64
 3   actual_price         1464 non-null   float64
 4   discount_percentage  1464 non-null   float64
 5   rating               1464 non-null   float64
 6   rating_count         1462 non-null   float64
 7   review_title         1464 non-null   str
 8   review_content       1464 non-null   str
dtypes: float64(5), str(4)
memory usage: 2.6 MB

In [92]:
# Calculate the average `discount_percentage`, `rating`, and `rating_count` for the whole dataset.
print("Mean:",df["discount_percentage"].mean())
print("Mean:",df["rating"].mean())
print("Mean:",df["rating_count"].mean())

Mean: 47.672366621067034
Mean: 4.096716826265389
Mean: 18307.376880984953

In [80]:
# Which category has the highest average rating? Use `groupby()` and `mean()`.

high = df.groupby("category")["rating"].mean()

In [81]:
high.sort_values(ascending=False).head(1)

category
Computers&Accessories|Tablets    4.6
Name: rating, dtype: float64

In [82]:
# Filter the dataframe to show products with `rating > 4.5` and `discount_percentage >

df[(df["rating"] > 4.5) & (df['discount_percentage'] > 50.0)]

,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,review_title,review_content
137,"10k 8k 4k HDMI Cable, Certified 48Gbps 1ms Ult...","Electronics|HomeTheater,TV&Video|Accessories|C...",999.0,2399.0,58.0,4.6,3664.0,"Fantastic Ultra High Speed HDMI cable,Amazing ...",Absolutely value for money. I connect it with ...
174,Syncwire LTG to USB Cable for Fast Charging Co...,Computers&Accessories|Accessories&Peripherals|...,399.0,1999.0,80.0,5.0,5.0,"Good,Superb quality,Good products nice one,Wo...",Product is good in quality. Working good with ...
324,"REDTECH USB-C to Lightning Cable 3.3FT, [Apple...",Computers&Accessories|Accessories&Peripherals|...,249.0,999.0,75.0,5.0,NaN,Awesome Product,Quick delivery.Awesome ProductPacking was good...
447,Spigen EZ Fit Tempered Glass Screen Protector ...,Electronics|Mobiles&Accessories|MobileAccessor...,999.0,2899.0,66.0,4.6,26603.0,"Easy to install but a bit slippery,Very good p...",I used my 13 pro without a screen guard for a ...
459,Spigen EZ Fit Tempered Glass Screen Protector ...,Electronics|Mobiles&Accessories|MobileAccessor...,999.0,2899.0,66.0,4.7,7779.0,"Easy to install,Best screen guard and the easi...",It is easy to install at home. The kit has all...
468,Spigen EZ Fit Tempered Glass Screen Protector ...,Electronics|Mobiles&Accessories|MobileAccessor...,999.0,2899.0,66.0,4.6,6129.0,"Best For It’s Money!🔥,Nice quality, but comes ...",It’s A Good Purchase For Long term Personally ...
571,"WeCool S5 Long Selfie Stick, with Large Reinfo...",Electronics|Mobiles&Accessories|MobileAccessor...,1799.0,3999.0,55.0,4.6,245.0,"Good,Good Product but Little expensive.,Happy ...","Good,Thoda sa kam stable hai, phone lagane ke ..."
1007,"WeCool S5 Long Selfie Stick, with Large Reinfo...",Electronics|Mobiles&Accessories|MobileAccessor...,1799.0,3999.0,55.0,4.6,245.0,"Good,Good Product but Little expensive.,Happy ...","Good,Thoda sa kam stable hai, phone lagane ke ..."
1119,Lint Remover Woolen Clothes Lint Extractor Bat...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",319.0,749.0,57.0,4.6,124.0,"good,Overall good product but got stop inbetwe...",https://m.media-amazon.com/images/W/WEBP_40237...
1223,"FIGMENT Handheld Milk Frother Rechargeable, 3-...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,699.0,1599.0,56.0,4.7,1729.0,"Nice product,Not as effective as claimed, just...","Value for money,Not as effective as claimed, j..."
1226,Zuvexa USB Rechargeable Electric Foam Maker - ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,499.0,1299.0,62.0,4.7,54.0,"Little kitchen helper,An amazing product,Very ...",The first time I tried it send the eggs and th...
1275,Multifunctional 2 in 1 Electric Egg Boiling St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,699.0,1599.0,56.0,4.7,2300.0,"Amazing! Value for money!,Very easy to use,2 i...","Worth buying for eggetarians,Working great so ..."
1289,Aquadpure Copper + Mineral RO+UV+UF 10 to 12 L...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,4999.0,24999.0,80.0,4.6,124.0,"service is excellent, installation guy is ver...","I like the service most and the product,Note: ..."
1293,Melbon VM-905 2000-Watt Room Heater (ISI Certi...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...",998.0,2999.0,67.0,4.6,9.0,"It's good,Happy to purchase,Product is really ...","It's good nd amazing product,Very nice produc..."
1299,"Instant Pot Air Fryer, Vortex 2QT, Touch Contr...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4995.0,20049.0,75.0,4.8,3964.0,"Loved it,Good product,Good product,It's easy t...",I have used multiple air fryers. But this one ...
1388,Campfire Spring Chef Prolix Instant Portable W...,"Home&Kitchen|Heating,Cooling&AirQuality|WaterH...",1499.0,3500.0,57.0,4.7,2591.0,"Felt very useful 👌 but cable is short,Good in ...","I like instant heating, I didn't get warranty ..."

In [83]:
# Sort the products by `rating` in descending order and display the top 10 rows.

df.sort_values("rating", ascending = False).head(10)

,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,review_title,review_content
174,Syncwire LTG to USB Cable for Fast Charging Co...,Computers&Accessories|Accessories&Peripherals|...,399.0,1999.0,80.0,5.0,5.0,"Good,Superb quality,Good products nice one,Wo...",Product is good in quality. Working good with ...
324,"REDTECH USB-C to Lightning Cable 3.3FT, [Apple...",Computers&Accessories|Accessories&Peripherals|...,249.0,999.0,75.0,5.0,NaN,Awesome Product,Quick delivery.Awesome ProductPacking was good...
775,Amazon Basics Wireless Mouse | 2.4 GHz Connect...,Computers&Accessories|Accessories&Peripherals|...,499.0,1000.0,50.0,5.0,23.0,"Very responsive and stylish mouse,Simply Aweso...",I really like this wireless mouse it has becam...
1299,"Instant Pot Air Fryer, Vortex 2QT, Touch Contr...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4995.0,20049.0,75.0,4.8,3964.0,"Loved it,Good product,Good product,It's easy t...",I have used multiple air fryers. But this one ...
1201,"Oratech Coffee Frother electric, milk frother ...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,279.0,499.0,44.0,4.8,28.0,"Oratech Best Coffee Frother,Great,My review ab...","Overall, I love this Oratech Coffee frother an..."
1145,Swiffer Instant Electric Water Heater Faucet T...,"Home&Kitchen|Heating,Cooling&AirQuality|WaterH...",1439.0,1999.0,28.0,4.8,53803.0,"Best Product,It’s expansive but it works well ...",Must buy best Fabulous product I recommend thi...
1223,"FIGMENT Handheld Milk Frother Rechargeable, 3-...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,699.0,1599.0,56.0,4.7,1729.0,"Nice product,Not as effective as claimed, just...","Value for money,Not as effective as claimed, j..."
1226,Zuvexa USB Rechargeable Electric Foam Maker - ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,499.0,1299.0,62.0,4.7,54.0,"Little kitchen helper,An amazing product,Very ...",The first time I tried it send the eggs and th...
1275,Multifunctional 2 in 1 Electric Egg Boiling St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,699.0,1599.0,56.0,4.7,2300.0,"Amazing! Value for money!,Very easy to use,2 i...","Worth buying for eggetarians,Working great so ..."
459,Spigen EZ Fit Tempered Glass Screen Protector ...,Electronics|Mobiles&Accessories|MobileAccessor...,999.0,2899.0,66.0,4.7,7779.0,"Easy to install,Best screen guard and the easi...",It is easy to install at home. The kit has all...

In [84]:
# Create a NumPy array from the numeric price column and find its `min`, `max`, `mean`, and `std`.

arr = df["actual_price"].to_numpy()
print("Min:",arr.min())
print("Max:",arr.max())
print("Mean:",arr.mean())
print("Std:",arr.std())

Min: 39.0
Max: 139900.0
Mean: 5447.002923497268
Std: 10874.55410991994

In [85]:
# Use `loc` and `iloc` to select a subset of rows and columns from the dataframe.

In [86]:
# Check for missing values using `isna()` and then remove or fill them using appropriate pandas methods.

df = df.dropna()

In [87]:
df.isna().sum()

product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
review_title           0
review_content         0
dtype: int64

In [88]:
# Compare `discounted_price` and `actual_price` using element-wise arithmetic and compute the discount amount.

df["discount_amt"] = df["actual_price"] - df["discounted_price"]

In [89]:
df["discount_amt"]

0        700.0
1        150.0
2       1700.0
3        370.0
4        245.0
         ...
1460     540.0
1461     765.0
1462     861.0
1463     491.0
1464     827.0
Name: discount_amt, Length: 1462, dtype: float64

In [90]:
# Reshape or stack NumPy arrays created from numeric columns to practice array operations and broadcasting.

#reshape
arr_2d = arr.reshape(61,24)
print(arr_2d)
print()
#broadcasting
new_price = arr*2
print(new_price)

[[ 1099.   349.  1899. ...   499. 22900.   199.]
 [19990.   699. 19999. ...   999.  1208.   475.]
 [  999.   395.  2199. ...   700.   899.   599.]
 ...
 [  599.   999.   199. ...  2400.  5295. 24999.]
 [  799.  2999.  2495. ... 10995.  3300.   400.]
 [ 1440.  3045.  3595. ...  3080.  1890.  3690.]]

[2198.  698. 3798. ... 6160. 3780. 7380.]

In [91]:
# Clean the numeric columns (`discounted_price`, `actual_price`, `discount_percentage`, `rating`, `rating_count`) and compute the correlation between `rating` and `rating_count`. Explain the result.

df[["discounted_price", "actual_price", "discount_percentage", "rating", "rating_count"]]

,discounted_price,actual_price,discount_percentage,rating,rating_count
0,399.0,1099.0,64.0,4.2,24269.0
1,199.0,349.0,43.0,4.0,43994.0
2,199.0,1899.0,90.0,3.9,7928.0
3,329.0,699.0,53.0,4.2,94363.0
4,154.0,399.0,61.0,4.2,16905.0
...,...,...,...,...,...
1460,379.0,919.0,59.0,4.0,1090.0
1461,2280.0,3045.0,25.0,4.1,4118.0
1462,2219.0,3080.0,28.0,3.6,468.0
1463,1399.0,1890.0,26.0,4.0,8031.0
1464,2863.0,3690.0,22.0,4.3,6987.0